export { ConfigTrigger } from "./ConfigTrigger";
export { ConfigMensajeria } from "./ConfigMensajeria";
export type { SubirImagenFn } from "./ConfigMensajeriaRica";
export { ConfigCRM } from "./ConfigCRM";
export { ConfigLogica } from "./ConfigLogica";
export { ConfigIntegracion } from "./ConfigIntegracion";
export { ConfigIA } from "./ConfigIA";
export { ConfigInterno } from "./ConfigInterno";
export { VariableSelector, VARIABLES_DISPONIBLES, type Variable } from "./VariableSelector";
export { TextareaConVariables } from "./TextareaConVariables";
